### PR TITLE
Add STM32duino support

### PR DESCRIPTION
**Pull request by karawin**
Compiled for bluePill STM32 under STM32duino.

### CODE REVIEW

**Comment by soligen2010** [comment]
Your pull request has a lot of old code in it that is trying to undo a lot of changes unrelated to what you are trying to update.  Looks like  you made changes to a very old version of the library then copied those files into this fork.  What you need to do is either re-base or get the current version of this fork and apply just your changes to the current version.

Also, this fork has already been modified to remove sei() and cli() in order to support the Arduino Due, so this fork may already work for you without needing any changes - please test it and see.

**Comment by karawin** [comment]
Yes sorry, i will check

**Comment by karawin** [comment]
In ClickEncoder.cpp
line 53 and 80 I made these change in order to compile under stm32duino
#if defined (__AVR__)
  uint8_t configType = (pinsActive == LOW) ? INPUT_PULLUP : INPUT;
#elif    defined(__arm__)  				// STM32DUINO    
  WiringPinMode configType = (pinsActive == LOW) ? INPUT_PULLUP : INPUT;
#endif

**Comment by soligen2010** [comment]
The current version compiles now for STM32duino. (I implemented it slightly differently. )   Please get the latest version and test it as I don't have a STM32duino board to test with.

Thanks for contributing.

**Comment by karawin** [comment]
Thanks. It works. Great.

**Pull request closed without merging**
